# Calendario

In [92]:
from datetime import datetime
from datetime import timedelta
import pandas as pd

lista_fechas = [1,2,4,5,6,8,9,11,12,13,15,16,18,19,20,25,26,27,32,33,34,36,37,39,40,41,43,44,46,47,48,53,54,55,60,
                61,62,64,65,67,68,69,74,75,76,81,82,83,85,86,127,128,134,135,141,142,144,145,146,148,149,151,152,153,
                155,156,158,159,160,162,163,165,166,167,169,170,172,173,174,176,177,179,180,181,186,187,188,193,194,195,197,
                198,200,201,202,207,208,209,214,215,216,218,219,221,222,223,225,226,228,229,230,232,233,242,243,244,249,250,
                251,253,254,256,257,258,260,261,263,264,265,270,271,272,277,278,279,281,282,284,285,286,291,292,293,295,296]

Begindatestring = "15-08-2022"
# carry out conversion between string
# to datetime object
Begindate = datetime.strptime(Begindatestring, "%d-%m-%Y")

dic_calendar = {}
for i, j in enumerate(lista_fechas):
    dic_calendar[i+1] = j
for i,j in dic.items():
#     t=[]
    date = Begindate + timedelta(days=j)
    
#     t.append(date.strftime('%d-%m-%Y'))
#     t.append(calendar.day_name[date.weekday()])
    
    dic_calendar[i] = date.strftime('%d-%m-%Y')
dic_calendar

{1: '16-08-2022',
 2: '17-08-2022',
 3: '19-08-2022',
 4: '20-08-2022',
 5: '21-08-2022',
 6: '23-08-2022',
 7: '24-08-2022',
 8: '26-08-2022',
 9: '27-08-2022',
 10: '28-08-2022',
 11: '30-08-2022',
 12: '31-08-2022',
 13: '02-09-2022',
 14: '03-09-2022',
 15: '04-09-2022',
 16: '09-09-2022',
 17: '10-09-2022',
 18: '11-09-2022',
 19: '16-09-2022',
 20: '17-09-2022',
 21: '18-09-2022',
 22: '20-09-2022',
 23: '21-09-2022',
 24: '23-09-2022',
 25: '24-09-2022',
 26: '25-09-2022',
 27: '27-09-2022',
 28: '28-09-2022',
 29: '30-09-2022',
 30: '01-10-2022',
 31: '02-10-2022',
 32: '07-10-2022',
 33: '08-10-2022',
 34: '09-10-2022',
 35: '14-10-2022',
 36: '15-10-2022',
 37: '16-10-2022',
 38: '18-10-2022',
 39: '19-10-2022',
 40: '21-10-2022',
 41: '22-10-2022',
 42: '23-10-2022',
 43: '28-10-2022',
 44: '29-10-2022',
 45: '30-10-2022',
 46: '04-11-2022',
 47: '05-11-2022',
 48: '06-11-2022',
 49: '08-11-2022',
 50: '09-11-2022',
 51: '20-12-2022',
 52: '21-12-2022',
 53: '27-12-2022',
 54: '28-12-2022',
 55: '03-01-2023',
 56: '04-01-2023',
 57: '06-01-2023',
 58: '07-01-2023',
 59: '08-01-2023',
 60: '10-01-2023',
 61: '11-01-2023',
 62: '13-01-2023',
 63: '14-01-2023',
 64: '15-01-2023',
 65: '17-01-2023',
 66: '18-01-2023',
 67: '20-01-2023',
 68: '21-01-2023',
 69: '22-01-2023',
 70: '24-01-2023',
 71: '25-01-2023',
 72: '27-01-2023',
 73: '28-01-2023',
 74: '29-01-2023',
 75: '31-01-2023',
 76: '01-02-2023',
 77: '03-02-2023',
 78: '04-02-2023',
 79: '05-02-2023',
 80: '07-02-2023',
 81: '08-02-2023',
 82: '10-02-2023',
 83: '11-02-2023',
 84: '12-02-2023',
 85: '17-02-2023',
 86: '18-02-2023',
 87: '19-02-2023',
 88: '24-02-2023',
 89: '25-02-2023',
 90: '26-02-2023',
 91: '28-02-2023',
 92: '01-03-2023',
 93: '03-03-2023',
 94: '04-03-2023',
 95: '05-03-2023',
 96: '10-03-2023',
 97: '11-03-2023',
 98: '12-03-2023',
 99: '17-03-2023',
 100: '18-03-2023',
 101: '19-03-2023',
 102: '21-03-2023',
 103: '22-03-2023',
 104: '24-03-2023',
 105: '25-03-2023',
 106: '26-03-2023',
 107: '28-03-2023',
 108: '29-03-2023',
 109: '31-03-2023',
 110: '01-04-2023',
 111: '02-04-2023',
 112: '04-04-2023',
 113: '05-04-2023',
 114: '14-04-2023',
 115: '15-04-2023',
 116: '16-04-2023',
 117: '21-04-2023',
 118: '22-04-2023',
 119: '23-04-2023',
 120: '25-04-2023',
 121: '26-04-2023',
 122: '28-04-2023',
 123: '29-04-2023',
 124: '30-04-2023',
 125: '02-05-2023',
 126: '03-05-2023',
 127: '05-05-2023',
 128: '06-05-2023',
 129: '07-05-2023',
 130: '12-05-2023',
 131: '13-05-2023',
 132: '14-05-2023',
 133: '19-05-2023',
 134: '20-05-2023',
 135: '21-05-2023',
 136: '23-05-2023',
 137: '24-05-2023',
 138: '26-05-2023',
 139: '27-05-2023',
 140: '28-05-2023',
 141: '02-06-2023',
 142: '03-06-2023',
 143: '04-06-2023',
 144: '06-06-2023',
 145: '07-06-2023'}

In [78]:
import calendar
calendar.day_name[Begindate.weekday()]

calendar.day_name[datetime.strptime(dic_calendar[5], '%d-%m-%Y').weekday()]

'Sunday'

In [89]:
# dates = pd.DataFrame.from_dict(dic_calendar).transpose()
# dates.columns = ['Fecha', 'Día']
# dates

          Fecha        Día
1    16-08-2022    Tuesday
2    17-08-2022  Wednesday
3    19-08-2022     Friday
4    20-08-2022   Saturday
5    21-08-2022     Sunday
..          ...        ...
141  02-06-2023     Friday
142  03-06-2023   Saturday
143  04-06-2023     Sunday
144  06-06-2023    Tuesday
145  07-06-2023  Wednesday

[145 rows x 2 columns]

In [91]:
# dates.to_csv('dates.csv', index = True)